---
- name: Install Python3, venv, pip
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: present

- name: Clone backend repo
  git:
    repo: "{{ backend_repo }}"
    dest: "{{ app_dir }}"
    version: "{{ backend_branch }}"
    force: yes

- name: Create virtualenv
  command: python3 -m venv {{ venv_path }}
  args:
    creates: "{{ venv_path }}/bin/activate"

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: Template systemd service
  template:
    src: app.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable & start backend service
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started
