version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    # Add a container name for easier reference
    container_name: sentiment-backend
    # Add CORS configuration as environment variable
    environment:
      - CORS_ORIGINS=http://localhost:3001

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    restart: always
    # Add a container name for easier reference
    container_name: sentiment-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Add environment variable for backend URL
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend