apiVersion: v1
kind: Secret
metadata:
  name: project-secrets
type: Opaque
data:
  CORS_ORIGINS: aHR0cDovL2xvY2FsaG9zdDozMDAx # http://localhost:3001
  REACT_APP_API_URL: aHR0cDovL2JhY2tlbmQtc2VydmljZTo4MDAw # http://backend-service:8000
