name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build backend Docker image
      run: docker build -t backend-test ./backend

    - name: Build frontend Docker image
      run: docker build -t frontend-test ./frontend

    - name: Run backend container
      run: docker run -d -p 8000:8000 --name backend-test backend-test

    - name: Run frontend container
      run: docker run -d -p 3000:3000 --name frontend-test frontend-test

    - name: Wait for services to be ready
      run: sleep 10

    - name: Test API health
      run: |
        curl --fail http://localhost:8000/ || exit 1

    - name: Test Frontend build (just JS linting)
      working-directory: ./frontend
      run: |
        npm install
        npm run lint || echo "Frontend linting failed but continuing"
